# Generated by Django 5.1.3 on 2024-12-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_relieflocation_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accident_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Duyệt'), ('resolved', 'Đã giải quyết')], default='pending', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='relieflocation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='relief_images/'),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='relieflocation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
